### ISSUE TITLE
之前图片图床不一样可以复读   现在无法复读

### ISSUE THREAD

**Issue by Vjjvj** [yejue/nonebot-plugin-plus-one#1]
[image:file={17368C1E-5A10-138C-50B8-407454593627}.jpg,url=https://gchat.qpic.cn/gchatpic_new/3870673431/4178762303-2698978234...,file_size=111064]

[image:file=17368C1E5A10138C50B8407454593627.jpg,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk4OTcz...,file_size=172867]'

**Comment by yejue** [comment]
两张图片的 size 不一样，不会认为是同一张的

**Comment by Vjjvj** [comment]
那就奇怪了，现在只要是新老版q转发和复制同一张图片发出去size都不一样，新转发新，旧转发旧才一样
